title: Samsung Chromebook Pro to Linux
email: steve@work.renlabs.com
description: >- # this means to ignore newlines until "baseurl:"
  Planning and executing an effort to repurpose an EOL chromebook to Linux.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://swork.github.io/samsung-chromebook-pro/"
github_username:  swork
theme: minima
plugins:
  - jekyll-feed
